
# Try on size 11
# Apply probes to train trajectories
interp-cli apply_cognitive_map_probe \
    --activations-dir data/activations/trajectories_train_single_step/size11 \
    --trajectories-dir data/trajectories_train_single_step/size11 \
    --probe-path data/probes_train_single_step/size11/cognitive_map_probe_mlp_1024.pt \
    --output-dir data/trajectories_with_probes/size11 \
    --layers 15 \
    --steps all \
    --prompt-suffix-indices -1
