# Download trajectories
# Overall activation gathering
interp-cli gather_activations \
    --trajectory-paths 'data/trajectories_train_single_step/size9/*.json' \
    --prompt-suffix-indices '-3:-1' \
    --output-indices '-16:-14' \
    --layers '7,15,23' \
    --steps '0' \
    --output-dir 'data/activations/trajectories_train_single_step/size9'

# 1. Extract activations from trajectories
interp-cli gather_activations \
    --trajectory-paths "data/trajectories_train_single_step/size9/*.json" \
    --output-dir "data/activations/trajectories_train_single_step/size9" \
    --layers "7,15,23" \
    --steps 0 \
    --prompt_suffix_indices -1

interp-cli gather_activations \
    --trajectory-paths "data/trajectories_train_single_step/size5/*.json" \
    --output-dir "data/activations/trajectories_train_single_step/size5" \
    --layers "7,15,23" \
    --steps 0 \
    --prompt_suffix_indices -1


interp-cli gather_activations \
    --trajectory-paths "data/trajectories_train_single_step/size7/*.json" \
    --output-dir "data/activations/trajectories_train_single_step/size7" \
    --layers "7,15,23" \
    --steps 0 \
    --prompt_suffix_indices -1

interp-cli gather_activations \
    --trajectory-paths "data/trajectories_train_single_step/size11/*.json" \
    --output-dir "data/activations/trajectories_train_single_step/size11" \
    --layers "7,15,23" \
    --steps 0 \
    --prompt_suffix_indices -1

interp-cli gather_activations \
    --trajectory-paths "data/trajectories_train_single_step/size13/*.json" \
    --output-dir "data/activations/trajectories_train_single_step/size13" \
    --layers "7,15,23" \
    --steps 0 \
    --prompt_suffix_indices -1

interp-cli gather_activations \
    --trajectory-paths "data/trajectories_train_single_step/size15/*.json" \
    --output-dir "data/activations/trajectories_train_single_step/size15" \
    --layers "7,15,23" \
    --steps 0 \
    --prompt_suffix_indices -1



------------------------------------------------------------------------------------------------
# 2. Prepare activations for grid tile probing
interp-cli prepare_activations_for_probing \
    --activations-dir data/activations/trajectories_train_single_step/size9 \
    --trajectories-dir data/trajectories_train_single_step/size9 \
    --probe-type grid_tile \
    --layers "15" \
    --prompt_suffix_indices -1

# 3. Train a probe
# layer 15
 interp-cli train_cognitive_map_probe \
    --train-data-path data/activations/trajectories_train_single_step/size9/cognitive_map_activations_l15_s0_suffix_-1_grid_tile_grid9.pt \
    --model-type mlp \
    --hidden-dims "1024" \
    --learning-rate 3e-4 \
    --weight-decay 0.001 \
    --num-epochs 200 \
    --batch-size 2048  \
    --device cuda \
    --verbose \
    --normalize \
    --subset 0.1 \
    --dropout 0.0 \
    --balance-classes
