# Repeat main exp for layer 7 and layer 23
for layer in 15 7 23; do
    echo "Training and applying probes for layer ${layer}"
    # Repeat for all layers
    # Prepare activations for probing
    echo "Preparing activations for probing for layer ${layer}"
    for size in 7 9 11 13 15; do
    interp-cli prepare_activations_for_probing \
        --activations-dir data/activations_train_single_step/size${size} \
        --trajectories-dir data/trajectories_train_single_step/size${size} \
        --probe-type grid_tile \
        --layers ${layer} \
        --prompt_suffix_indices "-3:-1"
    done

    # MLP probe 
    echo "Training MLP probe for layer ${layer}"
    for size in 7 9 11 13 15; do
    interp-cli train_cognitive_map_probe \
        --train-data-path data/activations_train_single_step/size${size}/cognitive_map_activations_l${layer}_s0_suffix_-3--1_grid_tile_grid${size}.pt \
        --output-path data/probes_train_single_step/size${size}/cognitive_map_probe_layer${layer}_suffix_-3--1_mlp_1024_full_no_eval.pt \
        --model-type mlp \
        --hidden-dims "1024" \
        --learning-rate 3e-4 \
        --weight-decay 0.001 \
        --num-epochs 200 \
        --batch-size 2048  \
        --device cuda \
        --verbose \
        --normalize \
        --subset 1.0 \
        --dropout 0.0 \
        --balance-classes \
        --eval-split 0.1
    done

    # Logistic regression probe
    echo "Training logistic regression probe for layer ${layer}"
    for size in 7 9 11 13 15; do
    interp-cli train_cognitive_map_probe \
        --train-data-path data/activations_train_single_step/size${size}/cognitive_map_activations_l${layer}_s0_suffix_-3--1_grid_tile_grid${size}.pt \
        --output-path data/probes_train_single_step/size${size}/cognitive_map_probe_layer${layer}_suffix_-3--1_lr_full_no_eval.pt \
        --model-type lr \
        --hidden-dims "1024" \
        --learning-rate 3e-4 \
        --weight-decay 0.001 \
        --num-epochs 200 \
        --batch-size 2048  \
        --device cuda \
        --verbose \
        --normalize \
        --subset 1.0 \
        --dropout 0.0 \
        --balance-classes \
        --eval-split 0.1
    done


    # Apply MLP probe
    echo "Applying MLP probe for layer ${layer}"
    for size in 7 9 11 13 15; do
        interp-cli apply_cognitive_map_probe \
            --activations-dir data/activations_test_full/size${size} \
            --trajectories-dir data/trajectories_test_full/size${size} \
            --probe-path data/probes_train_single_step/size${size}/cognitive_map_probe_layer${layer}_suffix_-3--1_mlp_1024_full_no_eval.pt \
            --output-dir data/trajectories_with_probes/layer${layer}/mlp/size${size} \
            --layers 15 \
            --steps all \
            --prompt-suffix-indices -3:-1
    done

    # Apply logistic regression probe
    echo "Applying logistic regression probe for layer ${layer}"
    for size in 7 9 11 13 15; do
        interp-cli apply_cognitive_map_probe \
            --activations-dir data/activations_test_full/size${size} \
            --trajectories-dir data/trajectories_test_full/size${size} \
            --probe-path data/probes_train_single_step/size${size}/cognitive_map_probe_layer${layer}_suffix_-3--1_lr_full_no_eval.pt \
            --output-dir data/trajectories_with_probes/layer${layer}/lr/size${size} \
            --layers 15 \
            --steps all \
            --prompt-suffix-indices -3:-1
    done
done