
# Gather activations
interp-cli gather_activations \
    --trajectory-paths 'data/trajectories_train_single_step/size11/*.json' \
    --prompt-suffix-indices '-3:-1' \
    --output-indices '-16:-14' \
    --layers '7,15,23' \
    --steps '0' \
    --output-dir 'data/activations/trajectories_train_single_step/size9'

# Size 11
interp-cli prepare_activations_for_probing \
    --activations-dir data/activations_train_single_step/activations_train_single_step/size11 \
    --trajectories-dir data/trajectories_train_single_step/size11 \
    --probe-type grid_tile \
    --layers "15" \
    --prompt_suffix_indices "-3:-1"

# 3. Train a probe
interp-cli train_cognitive_map_probe \
    --train-data-path data/activations_train_single_step/activations_train_single_step/size11/cognitive_map_activations_l15_s0_suffix_-3--1_grid_tile_grid11.pt \
    --output-path data/probes_train_single_step/size11/cognitive_map_probe_suffix_-3--1_mlp_1024_subset.pt \
    --model-type mlp \
    --hidden-dims "1024" \
    --learning-rate 3e-4 \
    --weight-decay 0.001 \
    --num-epochs 200 \
    --batch-size 2048  \
    --device cuda \
    --verbose \
    --normalize \
    --subset 0.1 \
    --dropout 0.0 \
    --balance-classes



# Post reasoning
interp-cli prepare_activations_for_probing \
    --activations-dir data/activations_train_single_step/activations_train_single_step/size11 \
    --trajectories-dir data/trajectories_train_single_step/size11 \
    --probe-type grid_tile \
    --layers "15" \
    --output_indices "all"




interp-cli train_cognitive_map_probe \
    --train-data-path data/activations_train_single_step/activations_train_single_step/size11/cognitive_map_activations_l15_s0_output_all_grid_tile_grid11.pt \
    --output-path data/probes_train_single_step/size11/cognitive_map_probe_output_all_mlp_1024_subset.pt \
    --model-type mlp \
    --hidden-dims "1024" \
    --learning-rate 3e-4 \
    --weight-decay 0.001 \
    --num-epochs 200 \
    --batch-size 2048  \
    --device cuda \
    --verbose \
    --normalize \
    --subset 0.1 \
    --dropout 0.0 \
    --balance-classes
