# 7x7 grids
interp-cli probe-predict \
openai/gpt-oss-20b \
data/trained_probes/size7_numenvs1000_trajectorysteps20/observability_full_full_prompt/grid_last_prompt_layer_20_x_y/probes/multiclass_probe_layer_20_gpu_mlp1024_normalized.pkl \
data/grids_for_testing/size7_numenvs1000_trajectorysteps20.csv \
20
